### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pasbi** [pasbi/ommpfritt#68]
This shows the priority and progress of the most urgent features.

- [x] create a `.travis.yaml` file working for ubuntu xenial. [this is a good starting point](https://github.com/probonopd/ommpfritt/blob/master/.travis.yml)
- [x] refactor the updating system. See also #59. The updating mechanism is currently arbitrary, inefficient (more updates than required), and not very stable. I think it can be designed much more elegantly.
- [x] Fix the bounding box manager (#69 )
- [x] Fix many small bugs. There are many small bugs like extending selection (Shift-key) does not work with brush-select or #65. They are very annoying and should be easy to fix. Fix them.
- [x] Here is some room to implement new small features (#67, #17, #7, ...) Don't implement new features before the tasks above are done.
- [x] Animations is the next big thing.
- [x] Procedural styles (nodes). I pretty much know what the front-end (GUI) will look like, but I have no idea how to design the back-end. Ideas welcome.
